version: '3.8'

services:
  app:
    image: merdanio/patriot-music-backend:latest
    ports:
      - "8000:8000"
    depends_on:
      - redis
    networks:
      - music_bot_network
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
volumes:
  postgres_data:

networks:
  music_bot_network:
    driver: bridge 