version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
      - ./app:/app/app
      - ./alembic:/app/alembic
      - ./main.py:/app/main.py
      - ./pyproject.toml:/app/pyproject.toml
      - ./uv.lock:/app/uv.lock
      - ./alembic.ini:/app/alembic.ini
    environment:
      - DB_USER=vladdremenko
      - DB_PASS=postgres
      - DB_HOST=db
      - DB_NAME=vladdremenko
      - DB_PORT=5432
      - DB_POOL_SIZE=20
      - DB_MAX_OVERFLOW=10
      - DB_POOL_TIMEOUT=30
      - DB_POOL_RECYCLE=1800
      - DB_ECHO=false
      - ENVIRONMENT=development
      - PYTHONPATH=/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload --reload-dir /app
    depends_on:
      - db
    networks:
      - music_bot_network
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=vladdremenko
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=vladdremenko
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - music_bot_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vladdremenko"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  music_bot_network:
    driver: bridge 