"""Add image field to Track model

Revision ID: 8e529f94fa08
Revises: ad2b2d31ef81
Create Date: 2025-02-19 03:10:12.726031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e529f94fa08'
down_revision: Union[str, None] = 'ad2b2d31ef81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('artist', sa.String(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_tracks_artist'), 'tracks', ['artist'], unique=False)
    op.create_index(op.f('ix_tracks_duration'), 'tracks', ['duration'], unique=False)
    op.create_index(op.f('ix_tracks_id'), 'tracks', ['id'], unique=False)
    op.create_index(op.f('ix_tracks_image'), 'tracks', ['image'], unique=False)
    op.create_index(op.f('ix_tracks_name'), 'tracks', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tracks_name'), table_name='tracks')
    op.drop_index(op.f('ix_tracks_image'), table_name='tracks')
    op.drop_index(op.f('ix_tracks_id'), table_name='tracks')
    op.drop_index(op.f('ix_tracks_duration'), table_name='tracks')
    op.drop_index(op.f('ix_tracks_artist'), table_name='tracks')
    op.drop_table('tracks')
    # ### end Alembic commands ###
