"""Add video table and video_url field to Track model

Revision ID: a3d0f5d02aa4
Revises: 8e529f94fa08
Create Date: 2025-02-19 23:23:15.776420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3d0f5d02aa4'
down_revision: Union[str, None] = '8e529f94fa08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('video_url', sa.String(), nullable=True))
    op.alter_column('tracks', 'duration',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_tracks_video_url'), 'tracks', ['video_url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tracks_video_url'), table_name='tracks')
    op.alter_column('tracks', 'duration',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('tracks', 'video_url')
    # ### end Alembic commands ###
